### ISSUE TITLE
Unable to use plugin on Mac Silicon

### ISSUE THREAD

**Issue by ruirodrigues-eyenov** [microsoft/cocoapods-pod-linkage#7]
This is the `Gemfile`:

```
source "https://rubygems.org"

gem "cocoapods-pod-linkage"
```

and this is the `Podfile`:

```
platform :ios, '12.0'
use_frameworks!

plugin 'cocoapods-pod-linkage'

target 'App' do
end
```

as soon as I add `plugin 'cocoapods-pod-linkage'` to Podfile I get an error:

```
[!] Your Podfile requires that the plugin `cocoapods-pod-linkage` be installed. Please install it and try installation again.
```

and the plugin is installed:

```
> bundle info cocoapods-pod-linkage
  * cocoapods-pod-linkage (0.0.1)
	Summary: CocoaPods plugin for configuring the linkage type of a specific pod.
	Homepage: https://github.com/microsoft/cocoapods-pod-linkage
	Path: /Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-linkage-0.0.1
```

**Comment by omarzl** [comment]
It runs fine for me in an M1
are you executing `bundle exec pod install` ?

**Comment by ruirodrigues-eyenov** [comment]
sorry, I guess this was wierd problem (a crash) on ruby perhaps... 
I was trying now and comment all pods to at least make that command running without error.
I isolated 2 pods, for example `pod 'Kronos'`, created a project with just that pod and after some tries it start working for some reason 🤷‍♂️
